# Set up notification options
notifications: 
  email:
    recipients:
      - deptrainhatkhoi@yahoo.com

    # change is when the repo status goes from pass to fail or vice versa
    on_success: change
    on_failure: always

# specify language
language: c

# non-root build
sudo: true

# specify language options

os:
- linux

# configure which branches to run
branches:
  # whitelist
  only:
    - master
    - devel

compiler: 
- gcc

script: 
- ./project_manager.sh -p

before_install:
  - sudo apt-get -qq update
